apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kafka-tls
  namespace: fruition
spec:
  secretTargetRef:
  - parameter: ca
    name: kafka-cluster-ca-cert
    key: ca.crt
  - parameter: cert
    name: kafka-keda
    key: user.crt
  - parameter: key
    name: kafka-keda
    key: user.key
